# Generated by Django 4.2.1 on 2023-05-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0002_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="post",
        ),
        migrations.AddField(
            model_name="category",
            name="post",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogging.post",
            ),
            preserve_default=False,
        ),
    ]
